#!/usr/bin/env node
// Writes schema/types.ts from the two JSON schemas, so the TypeScript types can't drift from
// the shapes the validator enforces.
// Run: node tools/gen-schema-types.ts          (rewrite schema/types.ts)
//      node tools/gen-schema-types.ts --check  (exit 1 if schema/types.ts is stale)
//
// It covers exactly the keywords bin/validate.ts accepts. `not`, `pattern` and the numeric and
// length bounds constrain values rather than shapes, so they have no type and are skipped.

import fs from 'fs';
import path from 'path';

type Schema = { [k: string]: any };

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'schema/types.ts');
const SOURCES = [
  { file: 'finding.schema.json', prefix: '' },
  { file: 'agent-results.schema.json', prefix: 'Agent' },
];

const pascal = (s: string) => s.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase());
const key = (k: string) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
const union = (parts: string[]) => [...new Set(parts)].join(' | ');

function typeName(ref: string, prefix: string): string {
  const m = /^(?:([\w.-]+\.json))?#\/\$defs\/(\w+)$/.exec(ref);
  if (!m) throw new Error(`unsupported $ref: ${ref}`);
  const source = SOURCES.find((s) => s.file === m[1]);
  return (source ? source.prefix : prefix) + pascal(m[2]);
}

function objectType(s: Schema, prefix: string, indent: string): string {
  const props = s.properties || {};
  const required = new Set<string>(s.required || []);
  const lines = Object.entries(props).map(([k, v]) =>
    `${indent}  ${key(k)}${required.has(k) ? '' : '?'}: ${toType(v as Schema, prefix, `${indent}  `)};`);
  const extra = s.additionalProperties;
  if (extra && extra !== true) lines.push(`${indent}  [k: string]: ${toType(extra, prefix, `${indent}  `)};`);
  if (!lines.length) return extra === false ? 'Record<string, never>' : 'Record<string, unknown>';
  return `{\n${lines.join('\n')}\n${indent}}`;
}

function toType(s: Schema, prefix: string, indent = ''): string {
  if (s.$ref) return typeName(s.$ref, prefix);
  if ('const' in s) return JSON.stringify(s.const);
  if (s.enum) return union(s.enum.map((v: unknown) => JSON.stringify(v)));
  const branches = s.oneOf ? s.oneOf.map((b: Schema) => toType(b, prefix, indent)) : null;
  if (!s.type) {
    if (branches) return union(branches);
    if (s.properties) return objectType(s, prefix, indent);
    return 'unknown';
  }
  const types: string[] = Array.isArray(s.type) ? s.type : [s.type];
  const base = union(types.map((t) => {
    switch (t) {
      case 'string': return 'string';
      case 'number': case 'integer': return 'number';
      case 'boolean': return 'boolean';
      case 'null': return 'null';
      case 'array': return s.items ? `${wrap(toType(s.items, prefix, indent))}[]` : 'unknown[]';
      case 'object': return objectType(s, prefix, indent);
      default: throw new Error(`unsupported type: ${t}`);
    }
  }));
  // A oneOf beside `type` narrows the base: every branch holds together with it.
  return branches ? `${base} & (${union(branches)})` : base;
}

const wrap = (t: string) => (/[|&]/.test(t) && !/^\{[\s\S]*\}$/.test(t) ? `(${t})` : t);

function generate(): string {
  const out = [
    '// Generated by tools/gen-schema-types.ts from schema/*.schema.json. Do not edit by hand;',
    '// change the schema and rerun the generator.',
    '',
  ];
  for (const { file, prefix } of SOURCES) {
    const doc = JSON.parse(fs.readFileSync(path.join(ROOT, 'schema', file), 'utf8'));
    for (const [name, def] of Object.entries(doc.$defs as Record<string, Schema>)) {
      if (def.description) out.push(`/** ${def.description.replace(/\*\//g, '*\\/')} */`);
      out.push(`export type ${prefix}${pascal(name)} = ${toType(def, prefix)};`, '');
    }
  }
  return out.join('\n');
}

const text = generate();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== text) {
    console.error('schema/types.ts is stale: run node tools/gen-schema-types.ts');
    process.exit(1);
  }
  console.log('schema/types.ts matches the schemas');
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}
