// Generated by tools/gen-schema-types.ts from schema/*.schema.json. Do not edit by hand;
// change the schema and rerun the generator.

export type Finding = {
  schema_version: 1;
  id: string;
  run_id: string;
  invariant_class: InvariantClass;
  cluster: ClusterKey;
  sites: Site[];
  flow: TaintFlow;
  context: SourceContext;
  lease: null | Lease;
  triage: null | Triage;
  gate: null | GateDecision;
  patches: Record<string, unknown>[];
  disposition: null | Record<string, unknown>;
  prior: null | Record<string, unknown>;
};

export type InvariantClass = "injection.sql" | "injection.command" | "injection.code" | "injection.template" | "injection.path" | "injection.ldap" | "injection.xml" | "injection.log" | "xss.reflected" | "xss.stored" | "xss.dom" | "deserialization.unsafe" | "ssrf" | "redirect.open" | "authz.missing" | "authn.weak" | "session.weak" | "crypto.weak" | "crypto.misuse" | "secret.hardcoded" | "randomness.weak" | "race.toctou" | "memory.unsafe" | "dos.uncontrolled" | "disclosure.sensitive" | "config.insecure" | "other";

export type ClusterKey = {
  invariant_class: InvariantClass;
  sink_symbol: string | null;
  source_class: string | null;
};

export type Site = {
  locus: Locus;
  observations: Observation[];
};

export type Locus = {
  file: string;
  symbol: string | null;
  sink_digest: string;
  line_at_scan: number;
};

export type Observation = {
  scanner: "semgrep" | "codeql";
  rule_id: string;
  rule_name: string | null;
  native_fingerprint: string | null;
  message: string;
  claimed: ClaimedSeverity;
  cwe: string[];
  owasp: string[];
  engine: string | null;
  suppressed_at_source: boolean;
  raw_pointer: string;
  seen_in_rounds: number[];
};

/** Each scanner's claim in its OWN vocabulary. Never collapsed to a shared enum: no meaning-preserving mapping exists. Only priority() and the report may read this. The gate cannot. */
export type ClaimedSeverity = {
  kind: "semgrep";
  severity: "ERROR" | "WARNING" | "INFO";
  impact: "LOW" | "MEDIUM" | "HIGH" | null;
  likelihood: "LOW" | "MEDIUM" | "HIGH" | null;
  confidence: "LOW" | "MEDIUM" | "HIGH" | null;
} | {
  kind: "codeql";
  problem_severity: "error" | "warning" | "recommendation" | null;
  security_severity: number | null;
};

export type FlowStep = {
  file: string;
  line: number;
  symbol: string | null;
  role: "source" | "propagation" | "sink";
  code: string;
  note: string | null;
};

/** Two constructors, never a sometimes-empty field. The triage prompt builder switches on kind. */
export type TaintFlow = {
  kind: "traced";
  provenance: "codeql_codeflows" | "semgrep_dataflow_trace";
  steps: FlowStep[];
} | {
  kind: "sink_only";
  sink: FlowStep;
  reason: "scanner_emitted_no_flow";
};

export type SourceContext = {
  scan_commit: string | null;
  source_hash: string;
  enclosing_excerpt: string;
};

export type Lease = {
  agent_id: string;
  role: "triage" | "fix" | "audit";
  started_at: string;
  ttl_s: number;
};

export type Severity = "critical" | "high" | "medium" | "low" | "informational";

/** Severity exists ONLY on the exploitable branch. Absent from the type elsewhere, so the gate cannot read a severity nobody established. */
export type Triage = {
  verdict: "exploitable";
  established_by: Provenance;
  contract: SecurityContract;
  severity: Severity;
  impact: string;
  likelihood: string;
  blast_radius: string;
} | {
  verdict: "not_exploitable";
  established_by: Provenance;
  refutation: {
    reason: "input_is_not_attacker_controlled" | "control_on_path_already_enforces_invariant" | "sink_is_not_the_dangerous_overload" | "defense_in_depth_gap_only" | "unreachable_code" | "test_or_fixture_or_generated_code" | "rule_semantics_mismatch";
    control: null | CodeRef;
    explanation: string;
  };
} | {
  verdict: "undecidable";
  established_by: Provenance;
  hypothesis: SecurityContract;
  blocker: {
    missing_fact: string;
    resolve_by: "owner_observation" | "local_check";
    plan: string;
  };
};

export type Provenance = "agent" | "carried_from_prior_run" | "deterministic_prepass";

export type CodeRef = {
  file: string;
  line: number;
  note: string;
};

export type SecurityContract = {
  invariant: string;
  violating_input: FixerVisibleText;
  enforcement_point: {
    file: string;
    symbol: string | null;
    rationale: FixerVisibleText;
  };
  witness: Witness;
  writable_scope: string[];
  forbidden_resolutions: FixerVisibleText[];
};

/** Any contract text that reaches the fixer's prompt. The invariant carries the stricter rule-id form check; these fields describe inputs, paths and hostnames, which that check would misread, so they reject the scanner's name and vocabulary only. A live triage wrote 'comments that silence the tool (nosemgrep, lgtm, codeql suppression)' into forbidden_resolutions; describe a forbidden move by its effect, never by the tool that would notice it. */
export type FixerVisibleText = string;

/** Strongest tier the repo supports: dynamic > executable > structural > argued. The pre-patch signal is mandatory on every mechanical tier; that is what a suppression cannot produce. */
export type Witness = {
  tier: "dynamic";
  harness_id: string;
  attack: HttpExchange;
  observable: Observable;
  control: FunctionalControl;
  expected_pre_fix: "observable_fires";
  expected_post_fix: "observable_absent";
} | {
  tier: "executable";
  framework: string;
  entrypoint: string;
  attack_input: string;
  asserts: string;
  command_template: string;
  control: null | FunctionalControl;
  expected_pre_fix: "fail";
  expected_post_fix: "pass";
} | {
  tier: "structural";
  rule_yaml: string;
  anchor: Locus;
  expected_pre_fix: "match";
  expected_post_fix: "no_match";
} | {
  tier: "argued";
  obstacle: "no_test_harness" | "no_runnable_entrypoint" | "no_app_harness" | "invariant_is_configuration" | "invariant_is_cryptographic_parameter" | "requires_external_service";
  why: string;
};

export type HttpExchange = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
  path: string;
  headers: Record<string, unknown>;
  query: Record<string, unknown>;
  body: Record<string, unknown>;
  as_principal: string;
};

/** Closed union so the blast radius of a successful witness is a design-time decision, not an agent's judgment mid-request. */
export type Observable = {
  kind: "status_code";
  equals: number;
} | {
  kind: "body_contains";
  canary: string;
} | {
  kind: "body_json_path";
  path: string;
  equals: unknown;
} | {
  kind: "header_present";
  name: string;
  matches: string;
} | {
  kind: "row_appears";
  query: string;
  in_fixture_db: true;
} | {
  kind: "reflected_unescaped";
  marker: string;
} | {
  kind: "latency_exceeds";
  ms: number;
  baseline_ms: number;
};

/** A legitimate request that must pass on BOTH trees. Without it, 'the attack stopped working' is satisfiable by disabling the endpoint. */
export type FunctionalControl = {
  kind: "http";
  exchange: HttpExchange;
  expect: Observable;
} | {
  kind: "existing_test";
  command_template: string;
} | {
  kind: "unavailable";
  why: string;
};

export type GateDecision = {
  action: "fix" | "report_only";
  threshold?: Severity;
  reason: "at_or_above_threshold" | "below_threshold" | "not_exploitable" | "undecidable";
};

/** Returned by a triage agent. Either a verdict or a split. */
export type AgentTriage = Triage | {
  split: {
    site_lines: number[];
    why: string;
  }[];
};

/** Returned by a fixer. cannot_fix is a real outcome, not a failure to try: a second independent mind reading the frozen contract may decline before any patch exists. */
export type AgentFix = {
  outcome: "patched";
  declared_files: string[];
  enforcement_note: string;
  witness_path?: string | null;
} | {
  outcome: "cannot_fix";
  reason: string;
};

/** Returned by an auditor that did not triage and did not fix this finding. Four verdicts, one of them named for the failure we most expect. */
export type AgentAudit = {
  verdict: "enforces_invariant" | "silences_rule" | "moves_trust" | "incomplete_enforcement";
  trace: {
    step: string;
    loc: CodeRef;
  }[];
  stopped_at: null | CodeRef;
  uncovered_siblings: CodeRef[];
  explanation: string;
} & ({
  verdict?: "enforces_invariant";
  stopped_at?: CodeRef;
  uncovered_siblings?: unknown;
} | {
  verdict?: "incomplete_enforcement";
} | {
  verdict?: "silences_rule" | "moves_trust";
  uncovered_siblings?: unknown;
});
